name: Studio Code Server - FORK
version: 5.10.2
slug: vscode
description: Fully featured Visual Studio Code (VSCode) experience integrated in the
  Home Assistant frontend.
url: https://github.com/hassio-addons/addon-vscode
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 1338
ingress_stream: true
panel_icon: mdi:microsoft-visual-studio-code
startup: services
init: false
arch:
- aarch64
- amd64
uart: true
hassio_api: true
hassio_role: manager
services:
- mysql:want
- mqtt:want
homeassistant_api: true
host_network: true
uart: true
usb: true
gpio: true
audio: true
apparmor: false
host_dbus: true
docker_api: true
privileged:
- NET_ADMIN
- SYS_ADMIN
- SYS_RAWIO
- SYS_TIME
- SYS_NICE
devices:
- /dev/mem
map:
- config:rw
- ssl:rw
- addons:rw
- media:rw
- share:rw
- backup:rw
journald: true
options:
  packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  config_path: str?
  packages:
  - str
  init_commands:
  - str
image: ghcr.io/hassio-addons/vscode/{arch}
